### References:
1. https://www.codecademy.com/enrolled/paths/build-deep-learning-models-pytorch


### Intro to Tensors
Tensors are the fundamental building blocks of neural networks in PyTorch. Similar to NumPy arrays, tensors act as storage containers for numerical data.

tensors: https://www.codecademy.com/resources/docs/pytorch/tensors

Most of the time, our data starts out in NumPy arrays or pandas DataFrames. In order to use the data in PyTorch, we have to convert these datatypes to tensors using PyTorch’s `torch.tensor()` method.

The `torch.tensor()` method takes two arguments:
- the numerical data (NumPy array, Python list, or Python numeric variable)
- the desired data type (the `dtype` parameter)
  
Common datatypes include `torch.int` for integers and `torch.float` for floats.

Throughout this lesson, we’ll be trying to build a neural network to predict the rent of an apartment. The dataset we’ll be using was produced by StreetEasy for our original Intro to Machine Learning course.

Here’s an example of how we could convert a single apartment’s rent to an integer tensor:

In [11]:
import numpy as np
import pandas as pd
import torch

In [17]:
# define the apartment's rent
rent = 2550
# convert to an integer tensor
rent_tensor = torch.tensor(
    rent, 
    dtype=torch.int)
display(rent_tensor)

tensor(2550, dtype=torch.int32)

Now, let’s create a tensor that includes more information about our apartment: `rent`, `size_sqft`, and `age`.

In [7]:
# create a numpy array with the rent in US dollars, size in square feet, and age in years
apt_array = np.array([2550, 750, 3.5])
# convert to a tensor of floats
apt_tensor = torch.tensor(
    apt_array, 
    dtype=torch.float)

Often, our data will start out as a pandas DataFrame. In this case, we need to use the `.values` attribute of the DataFrame to retrieve the data as a NumPy array:

In [19]:
apartments_df = pd.read_csv("./Datasets/manhattan.csv")
apartments_df = apartments_df[['rent', 'size_sqft', 'building_age_yrs']]

# convert a DataFrame named df to a PyTorch tensor
torch.tensor(
    apartments_df.values, 
    dtype=torch.float)

tensor([[2.5500e+03, 4.8000e+02, 1.7000e+01],
        [1.1500e+04, 2.0000e+03, 9.6000e+01],
        [4.5000e+03, 9.1600e+02, 2.9000e+01],
        ...,
        [1.6990e+03, 2.5000e+02, 9.6000e+01],
        [3.4750e+03, 6.5100e+02, 1.4000e+01],
        [4.5000e+03, 8.1600e+02, 9.0000e+00]])

Note that working with individuals columns of a DataFrame can occasionally cause problems due to dimension assumptions in torch.

One solution is to make sure the individual column is actually a full DataFrame by using two brackets to select it:

In [23]:
torch.tensor(
    apartments_df[['rent']].values,
    dtype=torch.float)

tensor([[ 2550.],
        [11500.],
        [ 4500.],
        ...,
        [ 1699.],
        [ 3475.],
        [ 4500.]])

Another is to use torch’s .`view(-1,1)` method to automatically adjust dimensions:

In [25]:
torch.tensor(
    apartments_df['rent'].values,
    dtype=torch.float).view(-1,1)

tensor([[ 2550.],
        [11500.],
        [ 4500.],
        ...,
        [ 1699.],
        [ 3475.],
        [ 4500.]])

In [ ]:
import pandas as pd, numpy as np, sys
print("pandas:", pd.__version__, "numpy:", np.__version__, "py:", sys.version)